from pydantic import BaseModel,Field
from typing import Annotated


class Prompt(BaseModel):
    user_input: Annotated[str, Field(..., description="The input provided by the user")]
    
class Response_output(BaseModel):
    response: Annotated[str, Field(..., description="The response generated by the Gemini model")]  